name: Server Helm Chart CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'containers/server-helm/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Helm unit tests
        uses: d3adb5/helm-unittest-action@850bc76597579183998069830d5fa8c3ef0ea34a # v2.5.0
        with:
          install-mode: if-not-present
          charts: containers/server-helm

      - name: Helm Lint
        # Validates Chart.yaml and values.yaml against your schema
        run: helm lint --set global.fqdn=example.org containers/server-helm

      - name: Run Unit Tests
        run: |
          # Executes tests defined in containers/server-helm/tests/
          helm unittest containers/server-helm

      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@5ccaecbbf012bcb1eeeab66e649db64a477ade8f # v1.0.0

      - name: Validate Kubernetes Manifests
        run: |
          # Render templates and validate against K8s and Traefik schemas
          helm template containers/server-helm --set global.fqdn=test.local | kubeconform \
            -summary -strict \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
